version: '3.8'

services:
  db:
    image: postgres:16
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: testa
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build: .
    container_name: my-backend-container
    ports:
      - "5000:5000"
    env_file:
      - .env
    depends_on:
      - db
    restart: always
    command: sh -c "npx prisma generate && npx prisma migrate deploy && npm run dev"

  frontend:
    build:
      context: .
      args:
        NEXT_PUBLIC_BASE_API: http://backend:5000
    container_name: my-frontend-container
    ports:
      - "3000:3000"
    depends_on:
      - backend
    restart: always

volumes:
  pgdata: